#!/bin/bash

# dotmng
# author: Sergio Francisco <sergiofsfilho@gmail.com>

CFG_DIR=${HOME}/.config/dotfiles
BACKUP_DIR=${CFG_DIR}/backup/
LOG=${CFG_DIR}/dotfiles.log
DOTFILES_INCLUDE=${CFG_DIR}/dotfilesinclude
DOTFILES_GIT_DIR=${HOME}/Projects/dotfiles
DOTFILES_FILES=$(find . -maxdepth 1 -name ".*" | grep -f $DOTFILES_INCLUDE)
DT=$(date +%Y%m%d%H%M%S)
COMMIT_DT=$(date +%Y-%m-%d)
COMMIT_HR=$(date +%H:%M:%S)

# Check if the file $DOTFILES_INCLUDE already exists.
if [ ! -f $DOTFILES_INCLUDE ]; then
	echo "The file $DOTFILES_INCLUDE wasn't found."
	echo "Create it and execute $0 again."
	exit 1
else
	echo "List of files to be included."
	cat $DOTFILES_INCLUDE
	echo ""
fi

function backup ()
{
# Check if the folder $BACKUP_DIR already exists.
# If don't, the script will create it.
if [ ! -d "$BACKUP_DIR" ]; then
	mkdir -p $BACKUP_DIR
fi

cd $HOME
tar czf ${BACKUP_DIR}/dotfiles-backup-${DT}.tar.gz $DOTFILES_FILES > /dev/null 2>&1

if [ "$?" -eq 1 ]; then
	echo "ERROR: The dotfiles backup wasn't created."
	exit 1
else
	echo "Backup file created."

fi
}

function push ()
{
	backup;
	#rsync -avzh $(find . -maxdepth 1 -name ".*" | grep -f /home/sfrancisco/.config/dotfiles/dotfilesinclude) /home/sfrancisco/Projects/
	#rsync -avzh $DOTFILES_FILES $DOTFILES_GIT_DIR 
	cd $DOTFILES_GIT_DIR
	pwd
	git add $(find . -maxdepth 1 -name ".*")
	#git commit -m "Dotfiles updated at $COMMIT_DT $COMMIT_HR"
	#git push origin master
}

function pull ()
{
	backup;
}

#function uninstall ()
#{
#}

#function includeFile ()
#{
#}

#function restore ()
#{
#}

if [ -z "$1" ]; then
	echo "Usage: $0 {push|pull|uninstall}"
	exit 1
else
	case $1 in
		backup)
			backup;
			;;
		push)
			push;
			;;
		pull)
			pull;
			;;
#		uninstall)
#			uninstall();
#			;;
#		restore)
#			restore();
#			;;
		*)
			echo "Action not recognized. Usage: $0 {install|update|uninstall|status|backup|}"
			;;
	esac
fi
